### ISSUE TITLE
Inquiry About Real-Time Demo Availability/Feasibility for GVHMR

### ISSUE THREAD

**Issue by ruoyiqiao** [zju3dv/GVHMR#2]
Hi, thanks for sharing this fascinating work!

I am relatively new to this area and find your approach very interesting. I’m interested in understanding how your method performs in real-time scenarios. Would it be possible to provide a real-time version of the demo, or would it be feasible to adapt the current codebase to enable real-time rendering and display?

I appreciate any insights you could provide on this!

**Comment by zehongs** [comment]
Hi, since our method is sequence-to-sequence, it isn't suitable for streaming data or real-time use cases.

**Comment by ruoyiqiao** [comment]
Thank you for your prompt reply! I understand. I’m curious if you know of any similar works that support real-time capabilities? Would approaches like WHAM also face similar limitations with real-time processing?

**Comment by zehongs** [comment]
Yes, WHAM (without post-processing) sounds like a good choice for you.

**Comment by ruoyiqiao** [comment]
Sounds great, I’ll look into WHAM further. Appreciate the recommendation!

**Comment by ruoyiqiao** [comment]
Sounds great, I’ll look into WHAM further. Appreciate the recommendation!

**Comment by YouJiacheng** [comment]
> Hi, since our method is sequence-to-sequence, it isn't suitable for streaming data or real-time use cases.

> Yes, WHAM (without post-processing) sounds like a good choice for you.

Actually WHAM only theoretically supports streaming (i.e. uses a uni-directional RNN), the official codebase of WHAM doesn't support streaming inference.
Users must refactor the inference scaffold and network definition to support streaming inference.
The preprocessing parts (YOLO, ViTPose, ViT Feature) can be easily refactored into streaming, but it's nontrivial to refactor the core  network of WHAM.

Importantly, when processing the same sequence without streaming, a non-linear RNN is significantly slower than a Transformer of similar size due to the lack of parallelism.

Thus, as long as GVHMR supports short sequences, it's much better than the existing implementation of WHAM.
