### ISSUE TITLE
Windows 10 installation 

### ISSUE THREAD

**Issue by Abocg** [zju3dv/GVHMR#6]
Sorry to bother again. Am trying to run it on windows 10. I managed to install all the requirements using anaconda  except pytorch3d-0.7.6. is there anything i can do to make it work if possible?

**Comment by zehongs** [comment]
We use PyTorch3D for rendering results and performing rotation conversions. You can try installing it with conda, as this is an official recommendation by pytorch3d team. However, we chose not to do so because it may require installing PyTorch via conda as well, which could be slow.

Check this link for more information: [PyTorch3D Installation Guide](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md).

**Comment by Abocg** [comment]
Thanks

**Comment by Abocg** [comment]
@zehongs manged to get it work thanks. I would highly appreciate your help if you could tell how to convert the .pt file to bvh. I want it for medical research as I have very little knowledge of programming in general. As far as i searched SMPL(-X) conversion needs .npz which I don't know how to get.
